companyblog/models.py
from email.policy import default
from companyblog import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key = True)
    profile_pic = db.Column(db.String(20), index = True, nullable = False, default = 'default.png')
    email = db.Column(db.String(64), index = True, unique = True)
    username = db.Column(db.String(64), index = True, unique = True)
    password = db.Column(db.String(128))

    posts = db.relationship('BlogPost', backref = 'author', lazy = True)

    def __init__(self, email, username, password):
        self.email = email
        self.username = username
        self.password_hash = generate_password_hash(password)
    
    def check_hashed_password(self, password):
        return check_password_hash(self.password_hash, password=password)
    
    def __repr__(self) -> str:
        return "Username: {self.username}"

class BlogPost(db.Model):
    users = db.relationship(User)
    id = db.Column(db.Integer, primary_key = True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable = False)
    title = db.Column(db.String(140), nullable = False)
    date = db.Column(db.DateTime, nullable = False, default = datetime.utcnow)
    text = db.Column(db.Text, nullable = False)

    def __init__(self, title, user_id, text) -> None:
        self.title = title
        self.user_id = user_id
        self.text = text

    def __repr__(self) -> str:
        return f"Title: {self.title}"

companyblog/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from flask_wtf.file import FileField, FileAllowed

from flask_login import current_user
from companyblog.models import User

class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Login")

class RegisterForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired(), EqualTo("pass_confirm", message="Passwords do not match!")])
    pass_confirm = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Register")

    def check_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError("This email is already under use!")

    def check_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError("This username has already been registered!")

class UpdateUserForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    username = StringField("Username", validators=[DataRequired()])
    picture = FileField("Profile Picture", validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField("Update")
    
    def check_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError("This email is already under use!")

    def check_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError("This username has already been registered!")

companyblog/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import os
from flask_login import LoginManager

app = Flask(__name__)

basedir = os.path.abspath(os.path.dirname(__file__)) 
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///'+os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)
Migrate(app, db)

login_manager = LoginManager(app=app)
login_manager.init_app(app=app)
login_manager.login_view = "users.login"

from companyblog.core.views import core
from companyblog.core.error_pages.handlers import error
from companyblog.users.views import users
app.register_blueprint(core)
app.register_blueprint(error)
app.register_blueprint(users)

companyblog/core/views.py
from flask import Blueprint, redirect, render_template

core = Blueprint("core", __name__)

@core.route("/")
def index():
    return render_template("index.html")

@core.route("/info")
def info():
    return render_template("info.html")

companyblog/users/views.py
from flask import redirect, render_template, Blueprint, request, url_for, flash
from flask_login import login_user, logout_user, current_user, login_required
from companyblog import db
from companyblog.models import User, BlogPost
from companyblog.users.forms import LoginForm, RegisterForm, UpdateUserForm
from companyblog.users.picture_handler import add_profile_picture

users = Blueprint("users", __name__)

@users.route("/")
def logout():
    logout_user()
    return redirect(url_for("core.index"))

@users.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("users.login"))
    return render_template("register.html", form=form)

@users.route("/login", methods = ["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash("Login successful!")
            next = request.args.get("next")
            if next == None or not next[0] == "/":
                next = url_for("core.index")
            return redirect(next)
    return render_template("login.html", form=form)

companyblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Company-Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
    <ul class="navbar navbar-expand-lg navbar-light bg-light">
        <li class="nav-link"><a href="{{url_for('core.index')}}">Home</a></li>
        <li class="nav-link"><a href="{{url_for('core.info')}}">Info</a></li>
        <li class="nav-link"><a href="{{url_for('core.index')}}">Home</a></li>
        <li class="nav-link"><a href="#">Login</a></li>
        <li class="nav-link"><a href="#">Logout</a></li>
        <li class="nav-link"><a href="#">Register</a></li>
    </ul>

    {% block content%}

    {% endblock %}

</body>
</html>

companyblog/templates/index.html
{% extends "base.html" %}

{% block content%}
    <div class="jumbotron">Hello!</div>
{% endblock %}

companyblog/templates/info.html
{% extends "base.html" %}

{% block content%}
    <div class="jumbotron">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda ducimus cupiditate dolorum minus fugiat unde quaerat praesentium eaque magni repellendus placeat ex harum ipsum illo, autem explicabo iure cum suscipit!</p>
    </div>
{% endblock %}

companyblog/templates/login.html
{% extends "base.html" %}

{% block content%}
    <form method="POST">
        {{form.hidden_tag()}}
        {{form.email.label}} {{form.email()}} <br>
        {{form.password.label}} {{form.password()}} <br>
        {{form.submit()}}
    </form>
{% endblock %}

companyblog/templates/register.html
{% extends "base.html" %}

{% block content%}
    <form method="POST">
        {{form.hidden_tag()}}
        {{form.email.label}} {{form.email()}} <br>
        {{form.username.label}} {{form.username()}} <br>
        {{form.password.label}} {{form.password()}} <br>
        {{form.pass_confirm.label}} {{form.pass_confirm()}} <br>
        {{form.submit()}}
    </form>
{% endblock %}